version: "3.9" 
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - database
    restart: always
  database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=testdatabase
    networks:
      - app-network
networks:
<<<<<<< HEAD
  app-network:
=======
  app-network:
>>>>>>> 107760734dfdb9ed4463877d11bd3aec3e41500c
